[package]
name = "attr"
version = "0.1.0"
authors = ["Andr√© Silva <andregs@users.noreply.github.com>"]
edition = "2018"

[lib]
proc-macro = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syn = "1.0.14"
quote = "1.0.2"
